# Project Manager Configuration File
# Hopefully this is pretty self explanatory...

Active Projects: "/Volumes/Vault/_Fifth Room Creative/_Current"
Dormant Projects: "/Volumes/Mirror/_Vault/Projects/Dormant"
Completed Projects: "/Volumes/Mirror/_Vault/Projects/Completed"