project_manager:
    active_directory: ~
    dormant_directory: ~
    archive_directory: ~

backup_profiles:
    test:   
        source: /Users/mike/Desktop
        snapshots:
            storage: /Users/mike/Development/nibs/refactor/testdir
            # How many hours between snapshots?
            interval: 1
            exclude:
                - .DS_Store
                - .svn
        backups:
            storage: ~
            max_backups: 20
            exclude:
                - .DS_Store
                
    vault:
        source: /Volumes/Vault
        snapshots:
            storage: ~
            interval: 2
            exclude:
                - .DS_Store
        backups:
            storage: ~
            max_backups: 30
            exclude:
                - .DS_Store
            