# Project Manager Configuration File
# (Don't use quotes or backslashes in paths with spaces - just type them as-is)

active: /Volumes/Vault/_Fifth Room Creative/_Current
dormant: /Volumes/Mirror/_Vault/Projects/Dormant
completed: /Volumes/Mirror/_Vault/Projects/Completed