vault:
    source: /Volumes/Vault
    snapshot directory: /Volumes/Mirror/_Vault/Snapshots
    backup directory: /Volumes/Mirror/_Vault/Weekly
    snapshots: 14
    exclude:
        - .DS_Store

dunder:
    source: /Volumes/Red
    snapshot directory: ~
    backup directory: ~
    snapshots: 14
    exclude:
        - .DS_Store

mifflin:
    source: /Volumes/Mifflin
    snapshot directory: ~
    backup directory: ~
    snapshots: 14
    exclude:
        - .DS_Store

nemo:
    source: /Volumes/120gb
    snapshot directory: ~
    backup directory: ~
    snapshots: 14
    exclude:
        - *.mp3
        - .DS_Store
