vault:
    source: /Volumes/Vault
    snapshot directory: /Volumes/Mirror/_Vault/Snapshots
    backup directory: /Volumes/Mirror/_Vault/Weekly
    hourly: 12
    daily: 7
    exclude:
        - .DS_Store

dunder:
    source: /Volumes/Red
    snapshot directory: ~
    backup directory: ~
    hourly: ~
    daily: 7
    exclude:
        - .DS_Store

mifflin:
    source: /Volumes/Mifflin
    snapshot directory: ~
    backup directory: ~
    hourly: ~
    daily: 7
    exclude:
        - .DS_Store

nemo:
    source: /Volumes/120gb
    snapshot directory: ~
    backup directory: ~
    hourly: ~
    daily: 7
    exclude:
        - *.mp3
        - .DS_Store
        
test:
    source: /Users/mike/Documents/manpages
    snapshot directory: /Users/mike/Desktop/manpage_snaps
    backup directory: /Users/mike/Desktop/manpage_backups
    snapshots: 4
    exclude:
        - .DS_Store

folio:
    source: /Users/mike/Development/folio
    snapshot directory: ~
    backup directory: /Users/mike/Desktop/folio
    snapshots: 7
    exclude:
        - .DS_Store
        - *.log

        
