---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: mysql
  :database: project_mgr
  :username: root
  :password: ~
  :host: localhost
  :socket: /tmp/mysql.sock
  :encoding: utf8

:test:
  <<: *defaults
  :database: project_mgr_test

:production:
  <<: *defaults
  :database: project_mgr